<footer class="footer">
  <div class="container">
  <div class="columns">
    <div class="column">
      <div class="media">
          <div class="media-left">
               <img src="/oneplusmg/images/1+MG_footer_logo_white.png" alt ="EU flag" width="125" />
			   <img src="/oneplusmg/images/eu-flag.png" alt ="EU flag" width="80" />
          </div>
          <p class="media-content mt-1 has-text-white">This project is funded by European Union's Horizon 2020 Research and Innovation programme under grant agreement No. 951724.</p>
      </div>
    </div>
    <div class="column has-text-right">
      <p><a href="https://www.linkedin.com/company/b1mg-project/" aria-label="Linkedin"><i class="icofont-linkedin has-text-white is-size-1 pr-2" title="LinkedIn"></i></a> <a href="https://twitter.com/B1MG_Project" aria-label="Twitter"><i class="icofont-twitter  has-text-white is-size-1 pr-3" title="Twitter"></i></a><a href="https://mailchi.mp/elixir-europe.org/become-part-of-the-b1mg-community" aria-label="mailchimp"><i class="icofont-letter has-text-white is-size-1" title="Newsletter"></i></a></p>
      <p class="mt-2"><a href="#" class="underline">b1mg-coordination@elixir-europe.org</a></p>
      <p class="mt-1"><a href="#" class="underline">Privacy</a> | <a href="#">Accessibility</a></p>
    </div>
  </div>
  <!--<div class="columns">
    <div class="column">
      <h2>About</h2>
      <ul>
        <li><a href="/about/how-organised">How the project is organised</a></li>
        <li><a href="/about/objectives">Objectives and key results</a></li>
        <li><a href="/about/participants">Participants</a></li>
        <li><a href="/about/guide-science">Simple guide to the science</a></li>
        <li><a href="/about/glossary">Glossary</a></li>
      </ul>
    </div>
    <div class="column">
      <h2>Work Packages</h2>
      <ul>
        <li><a href="/about/how-organised">How the project is organised</a></li>
        <li><a href="/about/objectives">Objectives and key results</a></li>
        <li><a href="/about/participants">Participants</a></li>
        <li><a href="/about/guide-science">Simple guide to the science</a></li>
        <li><a href="/about/glossary">Glossary</a></li>
      </ul>
    </div>
    <div class="column">
      <h2>Resources</h2>
      <ul>
        <li><a href="/about/how-organised">How the project is organised</a></li>
        <li><a href="/about/objectives">Objectives and key results</a></li>
      </ul>
    </div>
    <div class="column">
      <h2>News & events</h2>
      <ul>
        <li><a href="/about/how-organised">How the project is organised</a></li>
        <li><a href="/about/objectives">Objectives and key results</a></li>
      </ul>
    </div>
  </div>-->
  </div>
  <div class="cookie-banner columns is-centered">
    <div class="column is-8 is-size-6">
        <p>
          We use cookies to gather statistics on visits to the site, so that we can report to funders and improve the website. See our
          <a href="#">privacy page</a>.
        </p>
    </div>
    <div class="column is-narrow">
        <button class="button cookie-btn cookie-accept is-primary">
          Accept cookies
        </button>
    </div>
    <div class="column is-narrow">
        <button class="cookie-btn cookie-reject button is-primary">
          Reject
        </button>
    </div>
  </div>
</footer>


  </body>
</html>
