<footer class="footer">
  <div class="container">
  <div class="columns">
    <div class="column">
      <div class="media">
          <div class="media-left">
               <a href="https://elixir-europe.org"><img src="/images/elixir-logo.png" width="75" alt="ELIXIR logo" class="mr-4"/></a><img src="/images/eu-flag.png" alt ="EU flag" width="80" />
          </div>
          <p class="media-content mt-1 has-text-grey">This project is funded by European Union's Horizon 2020 Research and Innovation programme under grant agreement No. 951724.</p>
      </div>
    </div>
    <div class="column has-text-right">
      <p><a href="https://www.linkedin.com/company/b1mg-project/"><i class="icofont-linkedin has-text-primary is-size-1 pr-2" title="LinkedIn"></i></a> <a href="https://twitter.com/B1MG_Project"><i class="icofont-twitter  has-text-primary is-size-1 pr-3" title="Twitter"></i></a><a href="https://mailchi.mp/elixir-europe.org/become-part-of-the-b1mg-community"><i class="icofont-letter has-text-primary is-size-1" title="Newsletter"></i></a></p>
      <p class="mt-2"><a href="mailto:b1mg-coordination@elixir-europe.org" class="underline">b1mg-coordination@elixir-europe.org</a></p>
      <p class="mt-1"><a href="/privacy" class="underline">Privacy</a></p>
    </div>
  </div>
  <!--<div class="columns">
    <div class="column">
      <h2>About</h2>
      <ul>
        <li><a href="/about/how-organised">How the project is organised</a></li>
        <li><a href="/about/objectives">Objectives and key results</a></li>
        <li><a href="/about/participants">Participants</a></li>
        <li><a href="/about/guide-science">Simple guide to the science</a></li>
        <li><a href="/about/glossary">Glossary</a></li>
      </ul>
    </div>
    <div class="column">
      <h2>Work Packages</h2>
      <ul>
        <li><a href="/about/how-organised">How the project is organised</a></li>
        <li><a href="/about/objectives">Objectives and key results</a></li>
        <li><a href="/about/participants">Participants</a></li>
        <li><a href="/about/guide-science">Simple guide to the science</a></li>
        <li><a href="/about/glossary">Glossary</a></li>
      </ul>
    </div>
    <div class="column">
      <h2>Resources</h2>
      <ul>
        <li><a href="/about/how-organised">How the project is organised</a></li>
        <li><a href="/about/objectives">Objectives and key results</a></li>
      </ul>
    </div>
    <div class="column">
      <h2>News & events</h2>
      <ul>
        <li><a href="/about/how-organised">How the project is organised</a></li>
        <li><a href="/about/objectives">Objectives and key results</a></li>
      </ul>
    </div>
  </div>-->
  </div>
  <div class="cookie-banner has-background-grey-darker columns">
    <div class="column is-three-quarters has-text-white is-size-6">
        <p>
          We use cookies to gather statistics on visits to the site, so that we can report to funders and improve the website. See our
          <a href="/privacy">privacy page</a>.
        </p>
    </div>
    <div class="column">
        <button class="button cookie-btn cookie-accept is-danger">
          Accept cookies
        </button>
    </div>
    <div class="column">
        <button class="cookie-btn cookie-reject button has-background-grey has-text-white">
          Reject
        </button>
    </div>
  </div>
</footer>


  </body>
</html>
